name: CI Contrib

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}  # Ensure that only one instance of this workflow is running per Pull Request
  cancel-in-progress: true  # Cancel any previous runs of this workflow

jobs:
  helpers:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - mysql
          - sql-obfuscation
        os:
          - ubuntu-latest
    name: "helpers-${{ matrix.gem }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: "Test Ruby 3.2"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-helpers-${{ matrix.gem }}"
          ruby: "3.2"
      - name: "Test Ruby 3.1"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-helpers-${{ matrix.gem }}"
          ruby: "3.1"
      - name: "Test Ruby 3.0"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-helpers-${{ matrix.gem }}"
          ruby: "3.0"
          yard: true
          rubocop: true
          build: true
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-helpers-${{ matrix.gem }}"
          ruby: "jruby-9.4.6.0"

  propagators:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - ottrace
          - vitess
          - xray
        os:
          - ubuntu-latest
    name: "propagator-${{ matrix.gem }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: "Test Ruby 3.3"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-propagator-${{ matrix.gem }}"
          ruby: "3.3"
      - name: "Test Ruby 3.2"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-propagator-${{ matrix.gem }}"
          ruby: "3.2"
      - name: "Test Ruby 3.1"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-propagator-${{ matrix.gem }}"
          ruby: "3.1"
      - name: "Test Ruby 3.0"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-propagator-${{ matrix.gem }}"
          ruby: "3.0"
          yard: true
          rubocop: true
          build: true
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-propagator-${{ matrix.gem }}"
          ruby: "jruby-9.4.6.0"

  resource-detectors:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - resource-detector-azure
          - resource-detector-container
          - resource-detector-google_cloud_platform
        os:
          - ubuntu-latest
    name: "opentelemetry-${{ matrix.gem }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: "Test Ruby 3.3"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "3.3"
      - name: "Test Ruby 3.2"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "3.2"
      - name: "Test Ruby 3.1"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "3.1"
      - name: "Test Ruby 3.0"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          yard: true
          rubocop: true
          build: true
          ruby: "3.0"
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "jruby-9.4.6.0"

  processors:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - baggage
        os:
          - ubuntu-latest
    name: "processors-${{ matrix.gem }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: "Test Ruby 3.3"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-processor-${{ matrix.gem }}"
          ruby: "3.3"
      - name: "Test Ruby 3.2"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-processor-${{ matrix.gem }}"
          ruby: "3.2"
      - name: "Test Ruby 3.1"
        uses: ./.github/actions/test_gem
        with:
          gem:  "opentelemetry-processor-${{ matrix.gem }}"
          ruby: "3.1"
      - name: "Test Ruby 3.0"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem:  "opentelemetry-processor-${{ matrix.gem }}"
          ruby: "3.0"
          yard: true
          rubocop: true
          build: true
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' && steps.jruby_skip.outputs.skip == 'false' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-processor-${{ matrix.gem }}"
          ruby: "jruby-9.4.6.0"
