name: Markdown Checks

on:
  pull_request:
    paths:
      - '**/*.md'
      - .github/workflows/ci-markdown-checks.yml

permissions:
  contents: read
  pull-requests: write # required for posting PR review comments

jobs:
  markdownlint-check:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0

      # equivalent cli: markdownlint-cli2  "**/*.md" "#**/CHANGELOG.md"  --config .markdownlint.json
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          config: .markdownlint.json
          fix: false
          globs: |
            **/*.md
            !**/CHANGELOG.md

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

  spelling-check:
    name: Spelling Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: streetsidesoftware/cspell-action@v8
        with:
          # Files should be consistent with check:spelling files
          files: |
            **/*.md
          config: .cspell.yml
