name: File Checks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write # required for posting PR review comments

jobs:
  markdown-lint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Markdown Lint Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # equivalent cli: markdownlint-cli2  "**/*.md" "!**/CHANGELOG.md"  --config .markdownlint-cli2.yaml
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
        with:
          config: .markdownlint-cli2.yaml
          fix: false
          globs: |
            **/*.md

  markdown-link-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Markdown Link Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3 # v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

  renovate-config-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Renovate Config Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: "npm"
          node-version: "24"

      - name: install dependencies
        run: npm ci --ignore-scripts

      # equivalent cli: renovate-config-validator
      - name: "Renovate Lint Check"
        run: npm run check:lint:renovate

  ruby-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: RuboCop Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          cache: "npm"
          node-version: "24"

      - name: Install Ruby
        uses: ruby/setup-ruby@b90be12699fdfcbee4440c2bba85f6f460446bb0 # v1.279.0
        with:
          ruby-version: "3.2"

      - name: Install Tools
        run: npm ci --ignore-scripts && bundle install

      - name: "Lint all ruby files"
        run: |
          set -e # forces exit code to propagate
          npm run check:lint:ruby -- --format github

      - name: "Check all ruby source files"
        run: |
          set -e # forces exit code to propagate
          npm run check:souce:ruby -- --format github


  yaml-lint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: YAML Lint Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # equivalent cli: yamllint .
      - name: "YAML Lint Check"
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c #v3.1.1
        with:
          config_file: .yamllint

  spelling-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Spelling Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: streetsidesoftware/cspell-action@24fa8d3096a314ce263f39578744e9d9f8d80acf # v8.1.2
        with:
          use_cspell_files: true
          config: .cspell.yml
          suggestions: true
          treat_flagged_words_as_errors: true
