name: Markdown Checks

on:
  pull_request:
    paths:
      - '**/*.md'
      - .github/workflows/ci-markdown-checks.yml

permissions:
  contents: read
  pull-requests: write # required for posting PR review comments

jobs:
  markdownlint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # equivalent cli: markdownlint-cli2  "**/*.md" "#**/CHANGELOG.md"  --config .markdownlint.json
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
        with:
          config: .markdownlint.json
          fix: false
          globs: |
            **/*.md
            !**/CHANGELOG.md

  markdown-link-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3 # v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

  spelling-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Spelling Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: streetsidesoftware/cspell-action@e5a858a18b7e0b56e0342b1dcad796308b7341a2 # v8.1.1
        with:
          # Files should be consistent with check:spelling files
          files: |
            **/*.md
          config: .cspell.yml
