name: 'Component Owners'
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  run_self:
    permissions:
      pull-requests: write # required for assigning reviewers to PRs
    runs-on: ubuntu-latest
    name: Auto Assign Owners
    steps:
      - uses: dyladan/component-owners@58bd86e9814d23f1525d0a970682cead459fa783 # v0.1.0
        with:
          config-file: .github/component_owners.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
