name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Ruby
        uses: ruby/setup-ruby@675dd7ba1b06c8786a1480d89c384f5620a42647 # v1.281.0
        with:
          ruby-version: 3.4.8
      - name: Generate Gemfile.lock
        run: |
          echo "Finding all Gemfiles in the project..."
          echo "======================================="
          ORIGINAL_DIR=$(pwd)

          find . -type f -name "Gemfile" -not -path "*/example/*" -not -path "*/releases/*" | sort | while read gemfile; do
              gemfile_dir=$(dirname "$gemfile")

              # Change to the Gemfile's directory
              echo "Changing to directory: $gemfile_dir"

              cd "$gemfile_dir" || continue

              echo "Current directory: $(pwd)"
              echo "Creating lock file for: $gemfile"

              # Generate the Gemfile.lock files
              bundle lock || echo "Warning: Failed to generate lock file for $gemfile, continuing..."

              cd "$ORIGINAL_DIR" || exit 1
          done

      - uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry
