name: FOSSA scanning

on:
  push:
    branches:
      - main
    paths:
      - '**/Gemfile.lock'
      - '.github/workflows/fossa.yml'
  schedule:
    - cron: '0 15 * * 3' # Weekly on Wednesday at 15:00 UTC

permissions:
  contents: read

jobs:
  fossa:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry
