# This workflow is intended to catch issues with installation issues after a release
# If the jobs fail that means users will not be able to install the latest version of gems
# You may have to update and release gems that fail to install
name: Installation Tests

on:
  workflow_dispatch:
  schedule:
    # Everyday at 2 PM UTC
    - cron: "0 14 * * *"

permissions:
  contents: read

jobs:
  installation-tests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.4
          - 3.3
          - 3.2
    name: ${{ matrix.ruby-version }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        # ATTENTION: Dependabot does not know how to update shared actions file.
        # If you see it update setup-ruby here also update it as part of actions/test_gem/action.yml
      - uses: ruby/setup-ruby@675dd7ba1b06c8786a1480d89c384f5620a42647 # v1.281.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: "Install Latest Gem Versions on ${{ matrix.ruby-version }}"
        working-directory: releases
        run: ./run.sh
