# This workflow is intended to catch issues with installation issues after a release
# If the jobs fail that means users will not be able to install the latest version of gems
# You may have to update and release gems that fail to install
name: Installation Tests

on:
  workflow_dispatch:
  schedule:
    # Everyday at 2 PM UTC
    - cron: "0 14 * * *"

jobs:
  installation-tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.3
          - 3.2
          - 3.1
          - 3.0
    name: ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # ATTENTION: Dependabot does not know how to update shared actions file.
        # If you see it update setup-ruby here also update it as part of actions/test_gem/action.yml
      - uses: ruby/setup-ruby@v1.180.1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: "Install Latest Gem Versions on ${{ matrix.ruby-version }}"
        working-directory: releases
        run: ./run.sh
